version: '3'
services:
  action_server:
    build: 
      context: ./anga2.0
      dockerfile: Dockerfile_action
    ports:
     - "5055:5055"

  api:
    build: 
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  bot:
    build: 
      context: ./anga2.0
      dockerfile: Dockerfile_bot
    ports:
      - "5005:5005"