FROM python:3.9.13-slim-buster

RUN apt-get update && apt-get install -y build-essential

WORKDIR /anga2.0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .
# RUN cd bot

EXPOSE 5008

RUN rasa train

CMD ["rasa", "run", "--enable-api", "-p", "5008", "--cors", "*"]